name: dolfin_flutter
description: An app to capture data for the DOLFIN project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.4+204

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  _flutterfire_internals: ^1.3.13
  animate_do: ^3.1.2
  another_flushbar: ^1.10.28
  archive: ^3.4.9
  async: ^2.11.0
  awesome_dialog: ^3.1.0
  awesome_notifications: ^0.8.2
  characters: ^1.3.0
  cloud_firestore: ^4.13.2
  cloud_firestore_platform_interface: ^6.0.6
  cloud_firestore_web: ^3.8.6
  cloud_functions: ^4.5.5 
  cloud_functions_platform_interface: ^5.5.8
  cloud_functions_web: ^4.6.8
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  device_preview: ^1.0.0
  equatable: ^2.0.3
  firebase_auth: ^4.14.1
  firebase_auth_platform_interface: ^7.0.5
  firebase_auth_web: ^5.8.8
  firebase_core: ^2.23.0
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.8.1
  firebase_messaging: ^14.7.5
  firebase_messaging_platform_interface: ^4.5.14
  firebase_messaging_web: ^3.5.14
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_local_notifications: ^16.1.0
  flutter_local_notifications_linux: ^4.0.0+1
  flutter_local_notifications_platform_interface: ^7.0.0+1
  google_sign_in: ^6.1.6
  google_sign_in_android: ^6.1.20
  google_sign_in_platform_interface: ^2.4.2
  google_sign_in_web: ^0.12.1
  image: ^4.1.3
  intl: ^0.18.1
  js: ^0.6.7
  lints: ^3.0.0
  matcher: ^0.12.16
  material_color_utilities: ^0.5.0
  meta: ^1.10.0
  package_info_plus: ^5.0.1
#  package_info_plus_linux: 1.0.5
#  package_info_plus_macos: 1.3.0
#  package_info_plus_platform_interface: 1.0.2
#  package_info_plus_web: 1.0.6
#  package_info_plus_windows: 2.1.0
  path: ^1.8.3
  petitparser: ^6.0.1
  pointycastle: ^3.7.3
  shared_preferences_android: ^2.2.1
  shared_preferences_foundation: ^2.3.4
  simple_animations: ^5.0.2
  sizer: ^2.0.15
  shared_preferences: ^2.0.13
  source_span: ^1.10.0
  test_api: ^0.6.1
  timezone: ^0.9.2
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.0
  url_launcher_android: ^6.2.0
  url_launcher_ios: ^6.2.1
  url_launcher_macos: ^3.1.0
  win32: ^5.1.0
  xdg_directories: ^1.0.3

#dev_dependencies:
#  flutter_lints: ^1.0.0
#  flutter_launcher_icons: "^0.9.3"
#  flutter_test:
#    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Icon.png"
  #adaptive_icon_background: "assets/icons/Icon-BG.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
